-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, 
TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
B.GENDER AS GENDER, 
COUNT(DISTINCT(A.USER_ID)) AS USERS 
FROM ONLINE_SALE a INNER JOIN USER_INFO B ON B.USER_ID = A.USER_ID
WHERE GENDER is NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), B.GENDER
ORDER BY YEAR, MONTH, GENDER 
